# Generated by Django 6.0.7 on 2026-07-15 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='is_created',
            field=models.BooleanField(default=False),
        ),
    ]
