# Generated by Django 6.0.7 on 2026-07-20 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_tag_article_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='est_publier',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='article',
            name='nb_vue',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
